### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oxr463** [rofl0r/modern-autotools#1]
Really insightful article. I'm working on rewriting the build system for one of my projects and I would like to use this as a starting point.

See: choosealicense.com/no-permission

**Comment by rofl0r** [comment]
glad to hear you like the article. in my opinion the code snippets here are too trivial to even consider a license, but i now made it explicit:
https://github.com/rofl0r/modern-autotools/commit/c5b8a4d2a5adda795e49d61d3317251bddc42912
